application: scipihomepage
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# Static files
- url: /img
  static_dir: static/img
- url: /html
  static_dir: static/html
- url: /js
  static_dir: static/js
- url: /css
  static_dir: static/css

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
